import Link from 'next/link';
import data from '../../../../public/matchups/world-eaters-reserve-plan/plans.json';
import '../../../vod/vod.css';
import './reserve-plan.css';
const base=process.env.NEXT_PUBLIC_BASE_PATH??'';
const core='https://assets.warhammer-community.com/eng_01-06_warhammer40k_new40k_core_rules-was6fbu1ix-hfewhmxyiy.pdf';
const update='https://assets.warhammer-community.com/eng_wh40k_faction_pack_thousand_sons-zha93omuus-lqi5vkrcpq.pdf';
type Plan=typeof data.layouts[number];
function Map({plan,arrivals=false}:{plan:Plan;arrivals?:boolean}){
 const id=`reserve-${plan.variant}-${arrivals?'arrival':'deployment'}`;
 const spawn=plan.units.find(u=>u.id==='Sp')!;
 return <figure className="reserve-map"><h3>{arrivals?'2 · Candidate arrival pockets':'1 · Deployment and Spawn staging'}</h3><svg viewBox="-3 -3 65 50" role="img" aria-labelledby={`${id}-title ${id}-desc`}>
 <title id={`${id}-title`}>{`Layout ${plan.variant}: ${arrivals?'conditional reserve arrivals':'suggested deployment'}`}</title><desc id={`${id}-desc`}>{`Current terrain PNG. Blue deployment zone is Thousand Sons. ${arrivals?'Gold dashed pockets are places to check after enemy movement, not guaranteed legal drops.':'Unit labels are group anchors except Magnus, whose circle is a 100mm base. The Spawn arrow indicates a scoring intention, not a validated movement path.'}`}</desc>
 <defs><marker id={`${id}-arrow`} markerWidth="5" markerHeight="5" refX="4" refY="2.5" orient="auto"><path d="M0 0L5 2.5L0 5" fill="none" stroke="#df9d00" strokeWidth=".8"/></marker></defs>
 <image href={`${base}${plan.image}`} width="60" height="44" preserveAspectRatio="none"/>
 {Array.from({length:7},(_,i)=><text key={`x-${i}`} x={i*10} y="-1" textAnchor="middle" fill="#dae6ed" fontSize=".85">{i*10}″</text>)}{Array.from({length:5},(_,i)=><text key={`y-${i}`} x="-1" y={i*10+.5} textAnchor="end" fill="#dae6ed" fontSize=".85">{i*10}</text>)}
 {!arrivals&&<><line x1={spawn.x} y1={spawn.y} x2={plan.centralApproach.x} y2={plan.centralApproach.y} stroke="#a06400" strokeWidth=".35" strokeDasharray=".5 .4" markerEnd={`url(#${id}-arrow)`}/>{plan.units.map(u=><g key={u.id}><circle cx={u.x} cy={u.y} r={u.id==='M'?100/25.4/2:1.05} fill="#102b32" stroke="#67ffe0" strokeWidth=".2"/><text x={u.x} y={u.y+.35} textAnchor="middle" fill="#fff" fontSize={u.id==='D+B1'?'.85':'1.05'} fontWeight="700" paintOrder="stroke" stroke="#102b32" strokeWidth=".2">{u.id}</text></g>)}</>}
 {arrivals&&<><rect x={plan.scarabs.x-4} y={plan.scarabs.y-3} width="8" height="6" rx=".5" fill="#ffd26b" fillOpacity=".22" stroke="#805000" strokeWidth=".35" strokeDasharray=".6 .4"/><text x={plan.scarabs.x} y={plan.scarabs.y} textAnchor="middle" fill="#fff2c3" stroke="#382500" strokeWidth=".35" paintOrder="stroke" fontSize="1.25" fontWeight="700">Scarabs?</text><circle cx={plan.prince.x} cy={plan.prince.y} r={60/25.4/2} fill="#ffcf72" fillOpacity=".3" stroke="#805000" strokeWidth=".3" strokeDasharray=".4 .2"/><text x={plan.prince.x} y={plan.prince.y-2} textAnchor="middle" fill="#fff2c3" stroke="#382500" strokeWidth=".35" paintOrder="stroke" fontSize="1.25" fontWeight="700">Prince?</text></>}
 <text x="30" y="46" textAnchor="middle" fill="#c8d7df" fontSize=".9">{arrivals?'Check every enemy within 8″, physical fit, shooting and charge lanes':'M = actual base · other circles = unit-group anchors · not full formations'}</text>
 </svg><figcaption>{arrivals?'Conditional turn-two options, not a predicted board state. Clear friendly models first; choose another pocket if enemy screening or terrain prevents entry. The 8″ × 6″ Scarab box is a planning allowance, not a legal eleven-base placement.':'Blue side = your PA army; red = WE. Coordinates are inches from the upper-left corner. Swap the plan to the other agreed side when needed. H/E/C labels identify home, expansion and central objectives.'}</figcaption></figure>;
}
export default function Page(){return <main className="vod-site reserve-plan"><Link href="/matchups/world-eaters/">← Threat ranges and charge calculator</Link><h1>Scarabs and Prince in reserve: PA vs Purge</h1><p>20 September 2026 · 11th edition · your supplied 2,000-point Grand Coven list · current 26 August terrain artwork.</p>
<section className="vod-focus"><h2>Yes—with a shooting reply and a scoring route</h2><p>Reserve the ten Scarabs with the Crystal Terminator Sorcerer, and the winged Prince. Deploy two nearby support groups: Magnus + R2 + Tzaangors, and R1 + the Incandaeum Disc Sorcerer. The groups should help punish the same enemy commitment. Put Spawn within a legal normal move of a central scoring position and use unattached Enlightened to cover the approaches.</p><p><strong>The Scarabs must have a useful arrival even if they fail their charge.</strong> Shoot the exposed assault package first. A charge is optional: take it when it gains something worth the risk and does not pull the whole brick into the next Eightbound/Angron response. Protect a friendly-side landing instead of assuming Jakhals and Goremongers will leave the enemy backfield open.</p><p>This is the reserve-heavy alternative to the earlier on-board Scarab baseline. It protects 720 points during the opening, but leaves Magnus as your main early damage threat. Keep enough space and scoring presence to survive until the reserves contribute.</p></section>
<section className="vod-review-text"><h2>Reserve rules and the turn-order trap</h2><p><strong>720 points in reserve:</strong> 385 Scarabs + 130 Terminator Sorcerer + 205 winged Prince. This is 36% of your intended 2,000-point army, below the standard 50% / 1,000-point cap. Both reserve units have Deep Strike throughout their models. The plan assumes the Terminator Sorcerer joins the Scarabs.</p><p>Standard Deep Strike is more than 8″ from every enemy unit. Because a selected charge target must also be within the modified charge roll, an unmodified minimum-distance arrival charge needs <strong>9+ on 2D6: 27.8%, or 47.8% with one failed-roll re-roll</strong>. These are dice odds before terrain, physical fit, casualties or other modifiers. Keep the charge target in range after shooting casualties; do not budget the turn around the roll.</p><p><strong>Rapid Ingress costs 1CP, at the end of the opponent’s Movement phase, from battle round two.</strong> It exposes the Prince to the rest of that enemy turn. Normal Deep Strike and Rapid Ingress arrivals must still have legal space. Starting reserves ordinarily must arrive by the end of round three.</p><div className="reserve-table-wrap"><table><thead><tr><th>Your turn order</th><th>Scarabs</th><th>Winged Prince</th></tr></thead><tbody><tr><th>You go second</th><td>Normal Deep Strike in your turn 2; shoot, optional charge.</td><td>Ingress at the end of WE turn 2 movement → survive WE shooting/charges → move, shoot and consider a charge in your turn 2.</td></tr><tr><th>You go first</th><td>Normal Deep Strike in your turn 2; must weather WE turn 2 before the Prince’s main attack.</td><td>Ingress at the end of WE turn 2 movement → move, shoot and consider a charge in your turn 3. It cannot help your already-completed turn 2.</td></tr></tbody></table></div><p>If you go first and need Prince shooting immediately in your turn 2, use ordinary arrival instead. His optional Aetherstride allows a closer, more-than-6″ arrival and enhanced Dark Blessing, but forbids charging that turn. It only works in your Movement phase, so it does not provide a 6″ Rapid Ingress. Standard ingress followed by next-turn movement is the plan when you want his melee.</p><p><a href={core}>Core rules §§11.02–04, 15.07, 20.01–04, 24.09 ↗</a> · <a href={update}>TS update: Aetherstride, Crystal and Incandaeum ↗</a> · <a href="https://wahapedia.ru/wh40k11ed/factions/thousand-sons/Daemon-Prince-of-Tzeentch-with-Wings">Prince datasheet ↗</a> · <a href="https://wahapedia.ru/wh40k11ed/factions/thousand-sons/Sorcerer-In-Terminator-Armour">Terminator Sorcerer ↗</a></p></section>
<section className="vod-review-text"><h2>How the Magnus group works</h2><p><strong>Tzaangors toward the enemy, Magnus behind blocking terrain, Rubrics offset to the side.</strong> Do not line up Tzaangors → Rubrics → Magnus in one straight corridor. Leave Magnus a base-width exit around the ruin and keep the Rubrics from becoming the next easy contact after the screen dies. Use a compact coherent Tzaangor formation on the threatened lane, then check the actual enemy landing spaces around its ends and behind it.</p><p>A Tzaangor line blocks ground routes; it does not automatically stop Angron flying over it. Test where his entire 100mm base could land, and where he could finish after fighting. The terrain drawing cannot certify that Magnus’s wings are hidden from both Forgefiends. Check from their real positions after deployment.</p><p><strong>Screen with En and the unattached bow unit; preserve D+B1.</strong> These plans attach the Exalted Disc Sorcerer to one three-model bow Enlightened unit, keeping Incandaeum for the damage turn. D+B1 is one attached group, not an extra screen. Both bow entries from your supplied roster are represented. If you declare a different attachment, adjust that group before deployment. Robots hold/reinforce the home area and cover a landing lane; do not leave their job unassigned.</p><p><Link href="/tactics/screening/">Measured formations, flying landing spaces and post-fight contact examples →</Link></p></section>
<section className="vod-review-text"><h2>Spawn: a real scoring job, not an automatic sacrifice</h2><p>Your primary is <strong>Vital Link</strong>. Controlling a central objective at the end of your turn scores 2VP, plus accumulated operation markers on controlled central objectives. Its Maintain Control action can add a marker at turn end. From round two, holding a non-home objective at your Command-phase check is worth 4VP, with another 4VP if one is central. Pick a central objective you can contest repeatedly rather than hiding everything until turn two.</p><p>Start Maintain Control only when eligible. An advance or fall-back prevents starting an action; the acting unit cannot shoot or declare a charge, and moving again after starting normally prevents completion. Spawn have an 8″ move and OC 1 per model: they can do this job, but do not assume two Spawn out-control an occupied objective. Check a legal path and control at the completion point.</p><p>WE’s <strong>Destroyer’s Wrath</strong> rewards kills and holding more objectives. Sending a screen forward should buy scoring, deny a route, or expose a target you can remove. A 65-point unit killed without accomplishing one of those jobs is feeding their plan.</p><p><a href={`${base}/reference/11th-edition/cards/priority-assets/vital-link.png`}>Vital Link scoring</a> · <a href={`${base}/reference/11th-edition/cards/priority-assets/vital-link-back.png`}>Maintain Control action</a> · <a href={`${base}/reference/11th-edition/cards/purge-the-foe/destroyers-wrath.png`}>WE scoring</a> · <a href={`${base}/reference/11th-edition/official/event-companion.pdf#page=4`}>Multiple-central-objective FAQ</a> · <a href={core}>Core actions §16</a> · <a href="https://wahapedia.ru/wh40k11ed/factions/thousand-sons/Chaos-Spawn">Spawn datasheet</a></p></section>
<nav className="reserve-nav">{data.layouts.map(p=><a key={p.variant} href={`#layout-${p.variant.toLowerCase()}`}>Layout {p.variant} · {p.title}</a>)}</nav>
{data.layouts.map(plan=><section className="vod-game reserve-layout" key={plan.variant} id={`layout-${plan.variant.toLowerCase()}`}><h2>Layout {plan.variant} · {plan.title}</h2><p><strong>{plan.subtitle}</strong></p><p>{plan.deployment}</p><p>{plan.risk}</p><p><Link href={`/planner/?layout=${plan.plannerId}`}>Open this layout in the editable planner</Link> · <a href={`${base}${plan.image}`}>Terrain PNG</a> · <a href={`${base}${plan.sourceImage}`}>Source portrait artwork</a></p><div className="reserve-maps"><Map plan={plan}/><Map plan={plan} arrivals/></div><div className="reserve-table-wrap"><table><thead><tr><th>Map label</th><th>Unit / job</th><th>Group anchor (x, y)</th></tr></thead><tbody>{plan.units.map(u=><tr key={u.id}><th>{u.id}</th><td>{u.label}</td><td>({u.x}, {u.y})</td></tr>)}</tbody></table></div><p><strong>Spawn and primary:</strong> {plan.spawn}</p><p><strong>Arrivals:</strong> {plan.arrival}</p><p><strong>Response:</strong> {plan.response}</p><p className="vod-small">Starting suggestions, not a packed-model legality or line-of-sight proof. Except Magnus, circles are unit anchors; all models still need to fit wholly in your zone, in coherency, clear of walls and other bases. The gold arrival sketches show places to inspect after enemy movement, not guaranteed safe Deep Strike positions. Measure every enemy-to-arrival base gap and leave another legal fallback.</p></section>)}
<section className="vod-review-text"><h2>Before committing the reserves</h2><ol><li>At deployment, identify the actual Angron and regular Eightbound lanes. He has no advance-and-charge permission for Angron in this supplied build; use the current threat calculator, not the old blessing.</li><li>Keep at least 1CP available for Prince ingress. Do not assume that also pays for a charge re-roll or your other damage/defence stratagems.</li><li>After WE move, reject an ingress pocket that is visible to dangerous shooting or offers an easy charge. More than 8″ away alone is not safety.</li><li>On your turn, clear your own models from the eleven-model Scarab landing, place the entire unit legally, then take a useful shot. Leave the brick unengaged if preserving a later Crystal reposition is more valuable than the charge.</li><li>If no worthwhile forward pocket remains, use a deeper supporting landing. Do not lose starting reserves by waiting past the round-three deadline.</li></ol><p><a href="https://github.com/kaashif/40k-planner/blob/main/docs/world-eaters-reserve-plan.md">Saved plan and original request ↗</a> · <a href={`${base}/matchups/world-eaters-reserve-plan/plans.json`}>Map coordinates and image provenance</a></p></section>
</main>}
