import Link from 'next/link';
import { notFound } from 'next/navigation';
import lessons from '../../../../public/tactics/screening.json';
import '../../../vod/vod.css';
export function generateStaticParams(){return lessons.map(l=>({slug:l.slug}));}
export default async function Page({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const lesson=lessons.find(l=>l.slug===slug);if(!lesson)notFound();
 const colors:Record<string,string>={screen:'#71dcca',protected:'#7ab7f4',enemy:'#f191ab',candidate:'#f1cd7b'};
 return <main className="vod-site"><Link href="/tactics/screening/">← Screening tactics</Link><h1>{lesson.title}</h1><section className="vod-review-text"><p>{lesson.summary}</p><p>{lesson.rules}</p><p>All diagrams are illustrative local board sections in inches, viewed from above. Actual base radii are used. Teal = Tzaangors; blue = Scarab front; pink = enemy; gold/dashed = candidate endpoint. Axes give exact base-centre coordinates. The Scarab front shown is a local segment, not the entire eleven-model unit.</p></section>{lesson.figures.map((f,i)=><section className="vod-game" key={f.title}><h2>{f.title}</h2><div className="screen-example"><svg viewBox="-2 -1 27 28" role="img" aria-label={f.title} style={{width:'100%',maxWidth:650,background:'#111e24'}}><defs><pattern id={`${slug}-${i}-grid`} width="1" height="1" patternUnits="userSpaceOnUse"><path d="M1 0H0V1" fill="none" stroke="#31434a" strokeWidth=".035"/></pattern><marker id={`${slug}-${i}-arrow`} viewBox="0 0 6 6" refX="5" refY="3" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0L6 3L0 6" fill="none" stroke="#f1cd7b"/></marker></defs><rect width="24" height="25" fill={`url(#${slug}-${i}-grid)`}/>{Array.from({length:13},(_,n)=><g key={n}><text x={n*2} y="26" fill="#c0ccd5" fontSize=".55" textAnchor="middle">{n*2}</text><text x="-1" y={n*2+.2} fill="#c0ccd5" fontSize=".55">{n*2}</text></g>)}{f.models.map((m,j)=><circle key={j} cx={m.x} cy={m.y} r={m.r} fill={m.side==='candidate'?'none':colors[m.side]} stroke={colors[m.side]} strokeWidth=".1" strokeDasharray={m.side==='candidate'?'.2 .15':undefined}><title>{`${m.side}: centre (${m.x}, ${m.y}), diameter ${(m.r*2).toFixed(2)} inches`}</title></circle>)}{'arrow' in f&&f.arrow&&<line {...f.arrow} stroke="#f1cd7b" strokeWidth=".13" strokeDasharray=".3 .2" markerEnd={`url(#${slug}-${i}-arrow)`}/ >}{f.labels.map((l,j)=><text key={j} x={l.x} y={l.y} fill="#e9f5fa" fontSize=".6" textAnchor="middle" paintOrder="stroke" stroke="#111e24" strokeWidth=".15">{l.text}</text>)}</svg><ol>{f.notes.map(n=><li key={n}>{n}</li>)}</ol></div></section>)}<section className="vod-review-text"><h2>Use this at the table</h2><ul>{lesson.practice.map(p=><li key={p}>{p}</li>)}</ul><p>Rules and base sizes: {lesson.sources.map(s=><a key={s.url} href={s.url}>{s.label} ↗ · </a>)}</p></section><footer className="vod-footer"><nav>{lessons.filter(l=>l.slug!==slug).map(l=><Link key={l.slug} href={`/tactics/screening/${l.slug}/`}>{l.title}</Link>)}<Link href="/matchups/world-eaters/">Deployment examples</Link></nav></footer></main>
}
