'use client';
import {useState} from 'react';
import {opponentLists,type OpponentUnit} from './opponent-utils';
import type {PlannerMarker} from './planner-utils';
export default function EnemyModels({onAdd,onReserve,markers,reserves}:{reserves:PlannerMarker[];onReserve:(list:string,unit:OpponentUnit,enabled:boolean)=>void;onAdd:(list:string,units:OpponentUnit[])=>void;markers:PlannerMarker[]}){
 const [listId,setListId]=useState('joe'),[arquebus,setArquebus]=useState(false);
 const [rhino,setRhino]=useState({width:80,height:120}),[skorpius,setSkorpius]=useState({width:90,height:155});
 const list=opponentLists.find(l=>l.id===listId)!;
 const units=list.units.map(u=>({...u,models:u.models.flatMap(m=>m.shape==='hull'?[{...m,widthMm:(listId==='joe'?rhino:skorpius).width,heightMm:(listId==='joe'?rhino:skorpius).height}]:u.id==='rangers'&&arquebus?[{...m,count:9},{...m,name:'Ranger with arquebus',count:1,widthMm:60,heightMm:35.5}]:[m])}));
 const dimensions=listId==='joe'?rhino:skorpius,setDimensions=listId==='joe'?setRhino:setSkorpius;
 return <section className="enemy-models"><h3>Opponent lists</h3><label>Opponent<select aria-label="Opponent list" value={listId} onChange={e=>setListId(e.target.value)}>{opponentLists.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><p>{list.detachments} · 11th edition</p><p>{list.note}</p><p><a href="https://github.com/kaashif/40k-planner/blob/main/docs/opponent-list-rules.md" target="_blank" rel="noreferrer">Movement rules and sources ↗</a></p><label>Hull width mm (estimate)<input type="number" min="30" max="300" value={dimensions.width} onChange={e=>setDimensions({...dimensions,width:Math.min(300,Math.max(30,Number(e.target.value)))})}/></label><label>Hull length mm (estimate)<input type="number" min="30" max="300" value={dimensions.height} onChange={e=>setDimensions({...dimensions,height:Math.min(300,Math.max(30,Number(e.target.value)))})}/></label>{listId==='zak'&&<label><input type="checkbox" checked={arquebus} onChange={e=>setArquebus(e.target.checked)}/> Rangers include one arquebus</label>}<button onClick={()=>onAdd(listId,units)}>Add whole opponent list</button><p>Only missing models are added, opposite your player colour. Staging avoids other bases, but ignores terrain and deployment zones. Hull estimates are editable before adding. Remove the unit to change its loadout/footprint.</p>{units.map(u=>{const total=u.models.reduce((n,m)=>n+m.count,0),present=markers.filter(m=>m.rosterUnitId===`${listId}:${u.id}`).length;return <article className="opponent-unit" key={u.id}><strong>{u.name}</strong><p>{u.points} pts · {present}/{total} models added</p><p>{u.models.map(m=>`${m.count} × ${m.widthMm===m.heightMm?m.widthMm:`${m.widthMm} × ${m.heightMm}`} mm${m.shape==='hull'?' hull estimate':''} · M${m.move}″`).join('; ')}</p>{u.note&&<p>{u.note}</p>}<label><input type="checkbox" aria-label={`Deep strike ${u.name}`} checked={reserves.filter(m=>m.rosterUnitId===`${listId}:${u.id}`).length>=total} onChange={e=>onReserve(listId,u,e.target.checked)}/> Deep strike</label><button disabled={present>=total} onClick={()=>onAdd(listId,[u])}>Add {u.name}</button> <a href={u.source} target="_blank" rel="noreferrer">Datasheet ↗</a>{u.hullSource&&<> · <a href={u.hullSource} target="_blank" rel="noreferrer">Hull measurement ↗</a></>}</article>})}</section>
}
