'use client';
import {useEffect,useRef,useState} from 'react';
import layouts from '../../public/reference/11th-edition/data/event-layouts.json';
import {NAMED_PLANS_KEY,readNamedPlans,validatePlan,type PlanFile,type NamedPlan} from './plan-files';
export default function PlanManager({getPlan,onOpen,requestedId,ready,layoutId,armyId}:{getPlan:()=>PlanFile;onOpen:(plan:PlanFile,id:string)=>void;requestedId:string|null;ready:boolean;layoutId:string;armyId:string}){
 const [plans,setPlans]=useState<NamedPlan[]>([]),[selected,setSelected]=useState(''),[name,setName]=useState(''),[message,setMessage]=useState(''),[loaded,setLoaded]=useState(false);
 const input=useRef<HTMLInputElement>(null),processed=useRef('');
 useEffect(()=>{try{setPlans(readNamedPlans(localStorage.getItem(NAMED_PLANS_KEY)));setLoaded(true);}catch{setMessage('Saved-plan storage could not be read. Your existing data has been left intact.');}},[]);
 useEffect(()=>{
  const key=`${requestedId}:${layoutId}:${armyId}`;if(!loaded||!ready||!requestedId||processed.current===key)return;
  processed.current=key;const plan=plans.find(p=>p.planId===requestedId);
  if(!plan){setMessage('This saved plan is not available in this browser. Import its JSON file to use it here.');return;}
  try{onOpen(plan,plan.planId);setSelected(plan.planId);setName(plan.name);setMessage(`Loaded ${plan.name}.`);}catch(e){setMessage(e instanceof Error?e.message:'Could not load plan.');}
 },[requestedId,layoutId,armyId,loaded,ready,plans,onOpen]);
 function persist(next:NamedPlan[]){localStorage.setItem(NAMED_PLANS_KEY,JSON.stringify(next));setPlans(next);window.dispatchEvent(new Event('planner-plans-changed'));}
 function save(update=false){try{const current=validatePlan(getPlan());const plan:NamedPlan={...current,name:name.trim()||`${armyId} · ${layoutId}`,planId:update?selected:crypto.randomUUID(),savedAt:new Date().toISOString()};persist(update?plans.map(p=>p.planId===selected?plan:p):[...plans,plan]);setSelected(plan.planId);setName(plan.name);setMessage(`Saved ${plan.name} in this browser.`);}catch(e){setMessage(e instanceof Error?e.message:'Could not save plan.');}}
 function open(){const plan=plans.find(p=>p.planId===selected);if(!plan)return;try{onOpen(plan,plan.planId);setName(plan.name);setMessage(`Loaded ${plan.name}.`);}catch(e){setMessage(e instanceof Error?e.message:'Could not load plan.');}}
 function download(){const plan=getPlan();plan.name=name.trim()||plan.name||'Deployment';const url=URL.createObjectURL(new Blob([JSON.stringify(plan,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`${plan.name.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="plan-manager" aria-label="Save and load deployments"><label>Plan name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. PA B · going second" maxLength={120}/></label><button disabled={!loaded||!ready} onClick={()=>save()}>Save new plan</button><button disabled={!loaded||!selected||!ready} onClick={()=>save(true)}>Update selected save</button><label>Saved plans<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose a deployment</option>{plans.map(p=><option key={p.planId} value={p.planId}>{p.name} · {p.armyId??'necrons'} · {p.layoutId}</option>)}</select></label><button disabled={!selected} onClick={open}>Load saved plan</button><button disabled={!selected} onClick={()=>{try{persist(plans.filter(p=>p.planId!==selected));setSelected('');setMessage('Deleted selected save; the current board is unchanged.');}catch{setMessage('Could not delete save.');}}}>Delete save</button><button onClick={download}>Export JSON</button><button disabled={!loaded||!ready} onClick={()=>input.current?.click()}>Import JSON</button><input ref={input} type="file" accept="application/json,.json" hidden aria-label="Import deployment JSON" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{const p=validatePlan(JSON.parse(await file.text()));if(!layouts.layouts.some(l=>l.id===p.layoutId))throw new Error('Unknown layout in imported plan.');const plan:NamedPlan={...p,planId:crypto.randomUUID(),savedAt:new Date().toISOString()};persist([...plans,plan]);onOpen(plan,plan.planId);setSelected(plan.planId);setName(plan.name);setMessage(`Imported ${plan.name}.`);}catch(error){setMessage(error instanceof Error?error.message:'Import failed.');}finally{if(input.current)input.current.value='';}}}/><span className="plan-manager-help">Named saves include both armies and reserves. Stored in this browser; export JSON for a portable backup.</span>{message&&<span role="status" className="plan-manager-message">{message}</span>}</section>;
}
