'use client';
import {useState} from 'react';
import {chargeChance,threatRanges,threatBands,reachChance,type ThreatSettings} from './threat-utils';
import {applyThreatRules,ruleOptions} from './threat-rules';
export default function ThreatCalculator({value,onChange,label='Selected model',ruleTags=[]}:{value:ThreatSettings;onChange:(s:ThreatSettings)=>void;label?:string;ruleTags?:string[]}){
 const [gap,setGap]=useState(24);const effective=applyThreatRules(value,ruleTags);const ranges=threatRanges(effective);
 const number=(key:'move'|'scout'|'advance'|'charge'|'chargeBonus'|'advanceBonus',title:string,min:number,max:number)=><label>{title}<input type="number" min={min} max={max} step="1" value={value[key]??0} onChange={e=>onChange({...value,[key]:Math.min(max,Math.max(min,Number(e.target.value)))})}/></label>;
 return <section className="threat-calculator" aria-label="Threat range calculator"><strong>{label} · open-ground threat</strong><div className="rule-options">{ruleOptions.filter(r=>ruleTags.includes(r.tag)).map(r=><label key={r.id}><input type="checkbox" checked={(value.activeRules??[]).includes(r.id)} onChange={e=>onChange({...value,activeRules:e.target.checked?[...(value.activeRules??[]),r.id]:(value.activeRules??[]).filter(id=>id!==r.id)})}/>{r.label} <a href={r.source} target="_blank" rel="noreferrer">Rules ↗</a><small>{r.note}</small></label>)}{ruleTags.includes('advance-charge')&&<p>To Slake its Rage: Advance and Charge is permitted. Enable Include Advance to include its D6 in the charge bands. Scouts 8″ is pre-battle only.</p>}{ruleTags.includes('battle-lust')&&<p>Battle-lust charge reroll is included automatically for this attached unit.</p>}{ruleTags.includes('we')&&<p>11th edition: the blessing is +1 charge, not army-wide rerolls or Advance and Charge. Angron has no Advance and Charge in this list. His selected aura can ignore movement/Advance/charge modifiers; adjust negative inputs when relevant.</p>}</div><div className="threat-inputs">{number('move','Move inches',0,30)}<label><input type="checkbox" checked={value.useScout} onChange={e=>onChange({...value,useScout:e.target.checked})}/> Include Scout</label>{value.useScout&&number('scout','Scout inches',0,18)}<label><input type="checkbox" checked={value.useAdvance} onChange={e=>onChange({...value,useAdvance:e.target.checked})}/> Include Advance</label>{value.useAdvance&&<>{number('advance','Advance result',1,6)}<label><input type="checkbox" checked={value.advanceCharge} onChange={e=>onChange({...value,advanceCharge:e.target.checked})}/> Advance and charge permitted</label></>}{number('charge','Charge roll',2,12)}{number('chargeBonus','Extra charge modifier',-6,6)}{number('advanceBonus','Extra Advance modifier',-6,6)}</div>
 <p className="threat-results" role="status"><span style={{color:'#80bfff'}}>Scout {ranges.scout}″</span> · <span style={{color:'#64efbc'}}>Move {ranges.move}″</span>{ranges.advance!==null&&<> · <span style={{color:'#ffd16f'}}>Advance {ranges.advance}″</span></>} · <span style={{color:'#ff99b8'}}>Charge threat {ranges.charge===null?'no eligible unengaged target':`${ranges.charge}″`}</span></p>
 {value.useAdvance&&!effective.advanceCharge&&<p>Advance is an alternative to charging. The charge ring uses normal movement; it does not add the advance.</p>}
 <div className="threat-inputs"><label>Starting base-edge gap<input type="number" min="0" max="90" value={gap} onChange={e=>setGap(Math.max(0,Math.min(90,Number(e.target.value))))}/></label><label><input type="checkbox" checked={effective.rerollCharge??false} disabled={ruleTags.includes('battle-lust')} onChange={e=>onChange({...value,rerollCharge:e.target.checked})}/> Re-roll failed charge (e.g. Command Re-roll)</label><span>Chance with random 2D6: <strong>{(100*chargeChance(gap,effective,effective.rerollCharge)).toFixed(1)}%</strong></span></div>
 <label><input type="checkbox" checked={value.rerollAdvance??false} onChange={e=>onChange({...value,rerollAdvance:e.target.checked})}/> Advance reroll available (e.g. Command Re-roll)</label>
 <div className="threat-legend">{threatBands(effective).map(b=><span key={b.name} style={{color:b.color}}>{b.name}: <strong>{b.range}″</strong></span>)}</div>
 <p>Before rolling: Advance reach {(100*reachChance(gap,effective,'advance')).toFixed(1)}%; charge reach {(100*reachChance(gap,effective,'charge')).toFixed(1)}%. Solid bands: charge. Dashed bands: Advance. Percentages are the chance of reaching that distance, not a fraction of maximum range. The slider changes the selected percentage; the 80% reference remains. Scout has a separate fixed segment and is included once in the totals. Advance bands always show the alternative Advance move. Charge bands include random D6 Advance only when Include Advance and permission are enabled; otherwise they use normal movement. Charge-roll and Advance-result fields affect the scenario above, not probability bands.</p>
 <p>Rings are centred on the selected model, not the whole unit. They measure to the target’s nearest base edge. Scout applies before the first turn, only if every model has it. Advance/result and charge-roll inputs describe a scenario; charge odds roll fresh 2D6 and assume the entered Scout/Advance already happened. A +charge modifier never extends the 12″ target-selection cap.</p><p>These are open-ground upper bounds, not legal routes. Adjust inputs for flight costs and other modifiers; walls, coherency, enemy bases, landing space and follow-up fight moves are not simulated. Do not count Scout again after moving the model. Rerolls are once per roll, not stacked; ensure you have the relevant CP/ability. Reactive moves, embarkation and disembarkation are not added. <a href="https://assets.warhammer-community.com/eng_01-06_warhammer40k_new40k_core_rules-was6fbu1ix-hfewhmxyiy.pdf">Core rules §§9, 11, 21, 24 ↗</a></p>
 </section>;
}
