import Link from 'next/link';
import '../../vod/vod.css';
import '../world-eaters/reserve-plan/reserve-plan.css';
import './matchup.css';
const base=process.env.NEXT_PUBLIC_BASE_PATH??'';
const faction='https://wahapedia.ru/wh40k11ed/factions/adeptus-mechanicus/';
const official='https://assets.warhammer-community.com/eng_wh40k_faction_pack_adeptus_mechanicus-nnsofctxvp-ed7amkvryu.pdf';
const terrain='/matchups/world-eaters-reserve-plan/layout-c.png';
type Unit=[string,number,number];
const starts:Unit[]=[['M',54,21],['S',55,35],['R1',56,29],['R2',56,40],['D',58,32],['Rob',49,24],['Sp',47,37],['En',52,9],['B',57,6]];
const upper:Unit[]=[['M',54,21],['S',56,12],['R1',55,6],['R2',56,39],['D',59,10],['Rob',49,24],['Sp',45,6],['En',52,35],['B',57,42]];
const reply:Unit[]=[['M',46,24],['S',44,36],['R1',51,29],['R2',56,40],['D',54,32],['Rob',49,24],['Sp',38,34],['En',51,10],['B',56,6]];
function Diagram({variant}:{variant:'lower'|'upper'|'reply'}){
 const response=variant==='reply',top=variant==='upper',id=`admech-${variant}`;
 const units=response?reply:top?upper:starts;
 const enemies:Unit[]=response?[['K1',32,29],['K2',24,10],['Guns',14,20],['TA',19,31]]:[['K1',14,32],['K2',14,12],['Guns',8,21],['TA',12,27]];
 return <figure className="reserve-map admech-map"><h3>{response?'3 · Example response after Robots commit':top?'2 · Alternative: concentrate on the upper lane':'1 · Default: concentrate on the lower lane'}</h3><svg viewBox="-3 -3 66 51" role="img" aria-labelledby={`${id}-title ${id}-desc`}><title id={`${id}-title`}>{response?'Turn-two focus fire':'Longways Thousand Sons deployment'} — {variant}</title><desc id={`${id}-desc`}>Actual short-edge terrain PNG, 60 by 44 inches. Thousand Sons deploy on the right, beyond x=42; enemy examples are on the left. Magnus is a scaled 100mm base. Other labelled markers are unit anchors, not complete formations. Mint small circles show ten 32mm Tzaangor bases. Orange arrows indicate intended routes, not verified movement distances.</desc>
 <defs><marker id={`${id}-arrow`} markerWidth="5" markerHeight="5" refX="4" refY="2.5" orient="auto"><path d="M0 0L5 2.5L0 5" fill="#f39400"/></marker></defs>
 <image href={`${base}${terrain}`} width="60" height="44"/>
 {[0,10,20,30,40,50,60].map(x=><text key={x} x={x} y="-1" fill="#e5eef5" fontSize="1" textAnchor="middle">{x}″</text>)}
 <line x1="42" y1="0" x2="42" y2="44" stroke="#40e5ff" strokeWidth=".28" strokeDasharray=".7 .4"/>
 {response&&<circle cx="19" cy="31" r="12" fill="#ff6080" fillOpacity=".09" stroke="#b92952" strokeWidth=".25" strokeDasharray=".6 .4"/>}
 {!response&&Array.from({length:10},(_,i)=><circle key={i} cx={42.8+(i%2)*1.45} cy={(top?6:27.2)+Math.floor(i/2)*1.45} r={16/25.4} fill="#25ffe0" stroke="#093c3a" strokeWidth=".18"/>)}
 {!response&&<text x="40.8" y={top?10:31} fontSize="1.4" fontWeight="bold" fill="#073e3b">T</text>}
 {(response?[[46,24,34,28],[44,36,34,30]]:top?[[55,12,45,14],[54,20,51,14]]:[[55,35,46,35],[54,22,53,28]]).map(([x,y,xx,yy],i)=><path key={i} d={`M${x} ${y}L${xx} ${yy}`} stroke="#f39400" strokeWidth=".5" markerEnd={`url(#${id}-arrow)`}/>)}
 {[...enemies,...units].map(([label,x,y])=><g key={label}><circle cx={x} cy={y} r={label==='M'?100/50.8:1.35} fill={enemies.some(u=>u[0]===label)?'#751d39':'#083d48'} stroke={enemies.some(u=>u[0]===label)?'#ff9fb2':'#63ffe0'} strokeWidth=".22"/><text x={x} y={y+.4} textAnchor="middle" fontSize={label.length>2?'.9':'1.1'} fontWeight="bold" fill="white">{label}</text></g>)}
 <text x="30" y="46.5" textAnchor="middle" fontSize="1.1" fill="#d9eaf3">{response?'K1 isolated → focus fire · K2 distant → delay · TA circle = 12″ denial':'Enemy examples ← 24″ deployment gap → Thousand Sons · x ≥ 42″'}</text>
 </svg><figcaption>{response?'Illustrative later position, not a predicted turn or an automatic legal move. Only take these firing positions if terrain, ranges and the surviving second Robot block allow it. The Technoarcheologist circle is centre-based: allow for its base when measuring the actual 12″ exclusion.':'Magnus is wholly beyond the home terrain footprint in this drawing; verify the physical ruin and model visibility from every gun. S includes the Terminator Sorcerer; R1/R2 each include their Sorcerer. Only M and the ten T screen bases are drawn to scale. Fit all other bases and check coherency in the planner.'}</figcaption></figure>;
}
const roles=[
 ['M','Magnus','(54, 21)','Behind the home ruin, with the lower exit clear. His nearest base edge is about 10″ behind the deployment line. Pick the flank with fewer enemy gun angles.'],
 ['S','10 Scarabs + Terminator Sorcerer','(55, 35)','Start on board for this plan. Stage by the lower ruins, supporting Magnus’s target; retain Crystal for a later legal reposition. Eleven bases must fit.'],
 ['R1 / D','Rubrics + Sorcerer / standalone Disc','(56, 29) / (58, 32)','Support the damage flank; clear scoring units. Keep the Disc alive for Incandaeum. He does not lead Enlightened.'],
 ['R2 / Rob','Other Rubrics + Sorcerer / Sekhetars','(56, 40) / (49, 24)','Hold rear/near-side space and cover reinforcement routes. Advance the Sekhetars only when a useful firing opportunity justifies exposure.'],
 ['T','10 Tzaangors','x=42.8/44.25; y=27.2–33','Two coherent rows at the threatened approach. Check walls and routes around both ends; the formation is not a guarantee against every approach.'],
 ['Sp','2 Spawn','(47, 37)','Stage towards the lower central objective. Move out only to score, deny a route, or force a useful enemy commitment.'],
 ['En / B','Spear / single bow Enlightened unit','(52, 9) / (57, 6)','Cover the quiet flank and later scoring routes; stay hidden until needed. Do not commit both just to delay one unit.'],
 ['DP','Winged Daemon Prince','Reserve, conditionally','Rapid Ingress only into a protected legal pocket. If the gun coverage and 12″ denial leave no credible pocket, deploy hidden with the main group instead.'],
];
export default function Page(){return <main className="vod-site reserve-plan admech-analysis"><Link href="/">← All tools</Link><h1>Thousand Sons vs Zak’s Kastelan cohort</h1><p>11th edition · checked 20 September 2026 · your supplied 2,000-point Grand Coven list vs Cohort Cybernetica + Lords of the Forge.</p>
<section className="vod-focus"><h2>Fight one Robot block; make the other walk</h2><p>Keep Magnus and the Scarabs close enough to punish the same target. Use one cheap screen to delay the nearer four Robots, take useful objectives, and refuse an equal fight on both flanks. The objective is a winning board position, not killing all eight Kastelans.</p><p>The examples assume a Datasmith with each Robot block and fist loadouts. Zak’s export omits weapons, attachments and enhancement names. Confirm those before using the final threat plan. His other pieces are Cawl, Thulia, an Enginseer, a Technoarcheologist, ten Rangers, nine Servitors, three Ironstriders and two Disintegrators. The 300/330-point Robot prices reflect first/second-unit pricing; they do not establish different weapons.</p><p><a href="https://github.com/kaashif/40k-planner/blob/main/armies/thousand-sons-2000.json">Your saved roster</a> · <a href="https://github.com/kaashif/40k-planner/blob/main/armies/zak-opponents.json">Zak’s saved roster</a></p><nav className="reserve-nav"><a href="#deployment">Deployment diagrams</a><a href="#rules">Rules to watch</a><a href="#threats">Measured threats</a><a href="#reserves">Deep Strike</a></nav></section>
<section id="deployment"><h2>Longways deployment: choose your stronger lane</h2><p>This uses the existing <strong>short-edge map, layout C, with a 24″ gap</strong>: enemy on the left, you on the right. It is the PA-vs-Purge terrain example already on the site, reused to demonstrate tactics. Zak’s force disposition was not supplied, so this is not a claim that it is your prescribed AdMech mission map.</p><p><Link href="/planner/?layout=purge-the-foe-vs-priority-assets-c">Open the longways terrain in the planner</Link> · <a href={`${base}${terrain}`}>Terrain PNG</a> · <a href={`${base}/reference/11th-edition/maps/layout-35.jpg`}>Original terrain artwork</a></p><p><strong>Enemy legend:</strong> K1/K2 = four Kastelans plus an assumed Datasmith each; Guns = illustrative long-range firing group; TA = Technoarcheologist. Enemy markers are examples, not Zak’s full deployment. DP starts off-board in the conditional reserve version.</p><Diagram variant="lower"/><div className="reserve-table-wrap"><table><thead><tr><th>Label</th><th>Unit</th><th>Anchor in inches</th><th>Job</th></tr></thead><tbody>{roles.map(([label,unit,anchor,job])=><tr key={label}><th>{label}</th><td>{unit}</td><td>{anchor}</td><td>{job}</td></tr>)}</tbody></table></div><Diagram variant="upper"/><p><strong>Choose the upper version</strong> if it gives Magnus and the Scarabs better cover from the Ironstriders and Disintegrators. Use the same concentration principle; this is a separate arrangement on the actual terrain, not a mirrored promise of identical cover. Do not split Magnus and the Scarabs into opposite corners.</p></section>
<section className="vod-review-text"><h2>The first two turns</h2><ol><li><strong>Before turn one:</strong> identify the two Robot routes, enemy long-range gun positions, Technoarcheologist and any Vingh’s Wafers bearer. Leave Magnus a 100mm-base exit. Check real visibility, including his wings.</li><li><strong>Turn one:</strong> stage behind terrain and take a worthwhile objective with a cheap unit when possible. Avoid exposing Magnus for a few wounds on a fully supported Robot unit. A screen should earn points or buy a useful response.</li><li><strong>After the Robots commit:</strong> check where they can finish after killing the screen. Move valuable units out of multi-charge and consolidation routes. Feed a second screen only when it buys something; do not stack Rubrics immediately behind the first.</li><li><strong>Your damage turn:</strong> concentrate Magnus, Scarab shooting and useful rituals on one exposed block. If it remains heavily protected, remove Rangers, Servitors or a gun platform instead and keep scoring. Four Robots have 28 wounds before their Datasmith: Magnus alone is not a reliable removal plan.</li><li><strong>After the exchange:</strong> reposition while the second block crosses the board. Do not rely on tagging the Robots to stop their shooting or next charge.</li></ol><Diagram variant="reply"/><p>Direct Doombolt mortal wounds bypass save rolls, so they do not trigger Repulsor Grid. Incandaeum can permit the additional Doombolt attempt described by its rule; it is not guaranteed damage. Benevolence can still provide a mortal-wound Feel No Pain. Avoid pouring low-quality shots into good Robot saves merely to trigger reflected wounds.</p><p><a href="https://wahapedia.ru/wh40k11ed/factions/thousand-sons/">Thousand Sons rituals and enhancements</a> · <Link href="/tactics/screening/">Screening formations and post-fight contact</Link></p></section>
<section id="rules"><h2>What Zak’s rules change</h2><div className="reserve-table-wrap"><table><thead><tr><th>Rule / source</th><th>Effect to watch</th><th>Your response</th></tr></thead><tbody>
<tr><th><a href={faction}>Doctrina Imperatives · army</a></th><td>Protector improves BS, grants Heavy, and protects nearby Battleline-supported units against melee hits. Conqueror improves WS, grants Assault, and improves AP near Battleline. Selection is at the start of the round.</td><td>Check the active imperative. Rangers enable proximity benefits; Cawl can also become Battleline through his selected canticle.</td></tr>
<tr><th><a href={faction+'#Cohort-Cybernetica'}>Cyber-Psalm Programming · Cohort</a></th><td>Legio Cybernetica gains +2″ Move and +1 OC per model unless Battle-shocked: Kastelans move 8″ and are OC3 each.</td><td>Four Robots bring OC12 before their leader. A token screen does not automatically steal their objective.</td></tr>
<tr><th><a href={faction+'#Lords-of-the-Forge'}>War-Form Mantles · Lords</a></th><td>Tech-Priest models gain a 4++ and 5+++; their shooting-time ability can force an enemy Vehicle within 12″ to test Battle-shock at −1 on a 2+, or preserve hidden status for their ranged attacks.</td><td>These defensive saves apply to the Tech-Priest models, not every Robot. The enemy-Vehicle option does not target Magnus, a Monster.</td></tr>
<tr><th><a href={faction+'Cybernetica-Datasmith'}>Datasmith protocols</a></th><td>Start in Aegis (+1 Toughness); choose a persistent protocol in Command: Aegis, +2 ranged attacks, or +2 melee attacks.</td><td>Check which is active: T10 durability and six fist attacks per Robot are different protocol states.</td></tr>
<tr><th><a href={faction+'Kastelan-Robots'}>Kastelan durability and fists</a></th><td>T9 base, 7W each, 2+/5++. Unmodified ranged save rolls of 6 reflect mortal wounds. Twin fists are S12, AP−2, D3 with wound rerolls.</td><td>A four-model fist block in its melee protocol has 24 attacks before casualties. Keep the Scarabs out of an unprepared charge.</td></tr>
<tr><th><a href={faction+'Belisarius-Cawl'}>Cawl’s selected canticle</a></th><td>Can designate one enemy for army-wide hit rerolls against it; alternatively provides a Battleline/OC-support mode or a 6″ Stealth aura.</td><td>Know his choice before exposing Magnus. These are alternatives, not all three simultaneously.</td></tr>
<tr><th><a href={faction+'Thulia-Ghuld'}>Thulia’s Icon of War</a></th><td>Her chosen option can grant advance-and-charge to one Skitarii or Thulia unit within 6″. Kastelans are neither. Other options provide fall-back permission or both imperatives.</td><td>Thulia herself can threaten after advancing. Do not add that permission to the Robot calculator.</td></tr>
<tr><th><a href={faction+'Tech-priest-Enginseer'}>Enginseer</a></th><td>Repairs D3 wounds on one nearby model and grants a selected Vehicle model 5+++ until next Command phase.</td><td>The protection is on one model, not all four Robots. His proximity-based Lone Operative can prevent easy ranged removal.</td></tr>
<tr><th><a href={faction+'Skitarii-Rangers'}>Rangers</a> / <a href={faction+'Servitor-Battleclade'}>Servitors</a></th><td>Rangers have Scout 6″ and sticky objective control. Servitors with a Tech-Priest can act after advancing and shoot after starting an action.</td><td>Kill or displace the scoring support when Robots are inefficient targets. Merely leaving a Ranger-held objective empty does not take it from Zak.</td></tr>
<tr><th><a href={faction+'Ironstrider-Ballistarii'}>Ironstriders</a> / <a href={faction+'Skorpius-Disintegrator'}>Disintegrators</a></th><td>Ironstriders can shoot after advancing or falling back. Disintegrator ferrumite gains +1 to hit Monsters/Vehicles; belleros instead benefits against Infantry.</td><td>Confirm weapons and inspect their firing lanes before selecting your strong flank. Magnus is a Monster and a ferrumite target.</td></tr>
</tbody></table></div><h3>Command-phase buffs and key stratagems</h3><ul><li><strong>Motive Imperative, 1CP:</strong> +3″ Move, +1 Advance and +1 charge to the selected Vehicle. Robots become M11; this does not grant advance-and-charge.</li><li><strong>Benevolence of the Omnissiah, 1CP:</strong> 6+++ for the selected eligible unit, improved to 5+++ against mortal wounds.</li><li><strong>Transcendent Cogitation, 1CP:</strong> both imperatives on the selected eligible unit. <strong>Machine Spirit Resurgent, 1CP:</strong> a depleted eligible unit gains hit rerolls, plus wound rerolls below half-strength. Chip damage can leave a dangerous response.</li><li><strong>Scriptural Prognosis, 1CP:</strong> worsens incoming AP by one against an eligible Tech-Priest unit on an objective for that enemy unit’s attacks. A Datasmith-led block can qualify.</li><li><strong>Overloaded Safeguards, 1CP:</strong> an eligible Tech-Priest unit can shoot and charge after falling back. A Datasmith-led block can qualify.</li><li><strong>Unconfirmed enhancements:</strong> Vingh’s Wafers grants an attached Datasmith unit Mobile; this can invalidate a route plan based on ordinary Robot terrain restrictions. Necromechanic can cancel one failed-save attack’s damage per battle round near its bearer. Confirm enhancement names; do not infer them from the point differences.</li></ul><p><a href={official}>Official faction pack v1.2 and amendments</a> · <a href={faction}>Full detachment rules and stratagem conditions</a>. Many Cohort buffs are chosen in Zak’s Command phase: record which block received each one.</p></section>
<section id="threats"><h2>Robot threat ranges: measure base edge to base edge</h2><p>Open-ground distances from the starting base edge. No Scout, no advance-and-charge, no charge reroll in these rows. “80%” means at least an 80% chance to reach that distance; integer dice give discrete steps. The 50% charge column uses the planner’s median convention.</p><div className="reserve-table-wrap"><table><thead><tr><th>Robot state</th><th>Move</th><th>80% charge reach</th><th>50% charge reach</th><th>Maximum</th></tr></thead><tbody><tr><th>Cohort</th><td>8″</td><td>13″</td><td>15″</td><td>20″</td></tr><tr><th>+ Motive Imperative</th><td>11″</td><td>17″</td><td>19″</td><td>23″</td></tr></tbody></table></div><p>For example, a buffed Robot unit 19″ away moves 11″ and needs a charge roll of 7+ after its +1: <strong>58.3%</strong>, or <strong>82.6%</strong> with a full charge reroll. A unit 23″ away needs 11+ after +1: <strong>8.3%</strong>, or <strong>16.0%</strong> with the reroll. The 12″ target-selection cap prevents reaching a target initially 24″ away by simply adding 11+12+1.</p><p><strong>From the line on this longways map:</strong> the zones are 24″ apart. Robots cannot make a direct first-turn charge into your untouched deployment zone even with Motive’s 23″ maximum. That stops being true once you move forward or after their next movement. Shooting remains a threat.</p><p><strong>Advancing is a separate option:</strong> M8 gives a median 11.5″ and maximum 14″ move-plus-advance; Motive gives a median 15.5″ and maximum 18″. With Conqueror’s Assault, a 12″ flamer could therefore reach up to 26″/30″ from its initial base edge, subject to visibility and legal routes. It cannot then charge on the rules established for this Robot build.</p><p>Native charge/advance rerolls were not established for these Robots. Command Re-roll can improve one roll when legal and funded; weapon wound rerolls and Cawl hit rerolls do not reroll charges. Use the <Link href="/threat-ranges/">interactive calculator</Link> for Thulia’s advance-and-charge, different starting gaps and reroll scenarios.</p></section>
<section id="reserves" className="vod-focus"><h2>Who has Deep Strike?</h2><p><strong>None of Zak’s supplied units has native Deep Strike.</strong> Kastelans also gain none from the two listed detachments. Strategic Reserves can still threaten board edges; Rapid Ingress is a timing tool, not an ability that gives every unit Deep Strike.</p><p><strong>Your winged Prince, Scarabs and Terminator Sorcerer have Deep Strike.</strong> This plan starts the Scarab brick on the board and keeps its Crystal option. Reserve the Prince only with a credible ingress pocket; an arrival more than 8″ from enemies can still be visible or chargeable.</p><p><strong>Zak’s Technoarcheologist excludes enemy reinforcements within 12″ horizontally of its model.</strong> Check it for Deep Strike, Rapid Ingress and a Crystal return. Its location in the third diagram is illustrative; the real model determines the real denied area.</p><p>If you go second, ingress in the opponent’s turn two can prepare the Prince for your turn two. If you go first, ingress in the opponent’s turn two prepares your turn three. Do not assume a protected enemy-backfield pocket will survive.</p><p><a href={faction+'Technoarcheologist'}>Technoarcheologist</a> · <a href="https://wahapedia.ru/wh40k11ed/factions/thousand-sons/Daemon-Prince-of-Tzeentch-with-Wings">Winged Prince</a> · <a href="https://wahapedia.ru/wh40k11ed/factions/thousand-sons/Scarab-Occult-Terminators">Scarabs</a> · <a href="https://wahapedia.ru/wh40k11ed/factions/thousand-sons/Sorcerer-In-Terminator-Armour">Terminator Sorcerer</a> · <a href="https://assets.warhammer-community.com/eng_01-06_warhammer40k_new40k_core_rules-was6fbu1ix-hfewhmxyiy.pdf">Core reserves, charges and terrain rules</a></p></section>
</main>}
