import Link from 'next/link';
import LayoutA from './LayoutA';
import ThreatMap from './ThreatMap';
import ShootingTable from './ShootingTable';
import units from '../../../public/matchups/drukhari/seb-units.json';
import '../../vod/vod.css';
import '../world-eaters/reserve-plan/reserve-plan.css';
import './drukhari.css';
const base=process.env.NEXT_PUBLIC_BASE_PATH??'';
const waha='https://wahapedia.ru/wh40k11ed/factions/drukhari/';
const core='https://wahapedia.ru/wh40k11ed/the-rules/core-rules/';
const pack='https://assets.warhammer-community.com/eng_wh40k_faction_pack_drukhari-p7mpvgnmnn-clii96hzh6.pdf';
const strata=[
 ['Pounce on the Prey','Skysplinter','Movement: after Infantry disembark from a transport that made a normal move.','Use an assault disembark instead, enabling the charge. No extra passenger normal move is granted.'],
 ['Wraithlike Retreat','Skysplinter','End of Fight: Infantry that fought.','Normal/fall-back move. Non-Wyches must finish within boarding distance of a friendly transport and embark; Wyches need not board. Same-turn re-embarkation is permitted.'],
 ['Skyborne Annihilation','Skysplinter','Shooting: a unit that disembarked this turn, before it shoots.','Sustained Hits 1; Kabalites/Hand of the Archon get Sustained Hits 2 instead.'],
 ['Swooping Mockery','Skysplinter','Your Movement: a transport within 8″ of your unit after its normal/advance/fall-back move.','The transport can make a 6″ normal move. Do not commit an approach that depends on it staying put.'],
 ['Night Shield','Skysplinter','Your Shooting: a targeted Drukhari Vehicle.','4++ for that phase. Budget for this when trying to kill a Raider or Ravager.'],
 ['Vicious Blades','Skysplinter','Fight: a transport has selected targets.','After it fights, roll per passenger; 5+ deals one mortal to a target, maximum six. Wracks add +1 to rolls, but none are listed.'],
 ['Planned Strikes','Exhibition','Fight: Wych Cult unit selected to fight.','Unrestricted melee Lethal Hits; unlike the detachment baseline, this can work into Magnus.'],
 ['Sculpting the Stage','Exhibition','Movement: Wych Cult unit selected to advance/fall back.','That move does not bar starting an action. All other eligibility and completion conditions still apply.'],
 ['Acrobatic Display','Exhibition','Your Shooting: targeted Wych Cult unit.','5++ for that phase. Useful against shooting; not an improvement on a Wych’s existing 4++ in melee.'],
];
const threatRows=[
 ['Incubi on foot','7″ + 2D6','12″','14″','19″','No native advance-and-charge.'],
 ['Wyches on foot, empowered to charge','8″ + D6 + 2D6','16″','18.5″','26″','Charge-phase Pain token required.'],
 ['Succubus + Wyches, both rolls rerolled','8″ + D6 + 2D6','19″','21″','26″','Separate Movement and Charge phase empowerments; full-roll rerolls.'],
 ['Moved boat + Pounce, ordinary passengers','14″ + 3″ setup + 2D6','22″','24″','29″','1CP; normal-moving transport, not advancing.'],
 ['Raider + Pounce + Speed of the Kill Wyches','14″ + 6″ setup + 2D6','25″','27″','32″','Raider must select its 6″ Wych disembark mode.'],
 ['Advancing Venom + Rapid Deployment passengers','14″ + D6 + 3″ setup + 2D6','25″','27.5″','35″','Venom empowerment; see shock-disembark interpretation below.'],
];
function Table({headers,rows}:{headers:string[];rows:string[][]}){return <div className="reserve-table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=>j===0?<th key={j}>{v}</th>:<td key={j}>{v}</td>)}</tr>)}</tbody></table></div>}
export default function Page(){return <main className="vod-site reserve-plan drukhari-guide"><Link href="/">← All tools</Link><h1>Thousand Sons vs Seb’s Drukhari</h1><p>Raider? I hardly know her! · 1,990pts · LGT 40k Main Event · supplied BCP export inspected 16 September 2026, 21:20:44 UTC · rules reviewed 26 September 2026 · 11th edition.</p><p>This is analysis of the pasted list, not a recorded game. The supplied entries total 1,990 points. Stats below are the current linked profiles; transport assignments and Venom splits are not present in the export. Rule explanations are paraphrases except the two labelled short quotations.</p><nav className="reserve-nav"><a href="#layout-a">Your layout A plan</a><a href="#threat-map">Threat map</a><a href="#meta">Meta comparison</a><a href="#shooting">Your kill probabilities</a><a href="#mission">Your objectives</a><a href="#counter-scoring">Deny his scoring</a><a href="#plan">Matchup plan</a><a href="#rules">Army and detachments</a><a href="#threats">Threats and transports</a><a href="#units">Every unit and weapon</a><a href="#glossary">Stat glossary</a></nav>
<section id="mission" className="vod-focus"><h2>Priority Assets vs Recon: different missions for each player</h2><Table headers={['Player / primary','Every round: end of own turn','Round 2 onwards','End of battle']} rows={[
 ['You: Vanguard Operation','4VP if you completed a vanguard operation; 2VP if you destroyed at least one enemy unit that turn. These are once-per-turn awards, not per unit.','4VP for controlling at least one non-home objective at the end of your Command phase. In round five, use end of your turn instead.','10VP if you control the enemy home objective.'],
 ['Seb: Search and Scour','3VP for controlling at least one central objective; 2VP if he destroyed at least one enemy unit that started that turn within terrain.','4VP PER non-home objective controlled at the end of his Command phase. In round five, use end of his turn instead.','5VP if no enemy units are wholly within his territory.'],
 ]}/><p><strong>Your action:</strong> in your Shooting phase, one eligible unit within a terrain area in the opponent’s territory can start Vanguard Operation, once per turn. It completes at the end of your turn if no enemy unit is within that terrain area. It does not require a different terrain area each turn.</p><p><strong>Territory means the opponent’s half of the battlefield, not just their deployment zone.</strong> Agree the boundary and qualifying terrain areas on your chosen layout. A unit doing the action normally cannot shoot or charge; an advance/fall-back ordinarily prevents starting it. Moving again or leaving the board normally prevents completion. Do not shoot with the intended action unit first.</p><p><strong>Your scoring plan:</strong> preserve one non-home objective, remove one affordable enemy unit per turn when possible, and build a protected route to an enemy-half terrain area. That can yield 4 + 2 + 4VP in a round-two-onward turn. You do not gain extra holding points simply by matching his objective count. Contest additional objectives to deny his 4VP-per-objective scoring.</p><p><a href={`${base}/reference/11th-edition/cards/priority-assets/vanguard-operation.png`}>PA scoring card</a> · <a href={`${base}/reference/11th-edition/cards/priority-assets/vanguard-operation-back.png`}>Vanguard action card</a> · <a href={`${base}/reference/11th-edition/cards/reconnaissance/search-and-scour.png`}>Recon scoring card</a> · <a href={`${core}#Actions`}>Action rules</a> · <a href={`${base}/reference/11th-edition/official/event-companion.pdf`}>Event Companion and territory definitions</a></p></section>
<section id="counter-scoring" className="vod-focus"><h2>How to deny Seb’s Search and Scour points</h2><Table headers={['His scoring condition','Your counter','Important timing']} rows={[
 ['4VP per non-home objective','Clear or out-control an exposed scoring unit on your turn. Denying one objective removes 4VP from the next check. Kill or out-control sticky Kabalite objectives; an empty objective is not automatically neutral.','Normally his next Command phase; round five switches to his end of turn.'],
 ['3VP for any central objective','Deny control of every central objective at his turn end. Removing him from only one is insufficient if he controls another. Layer screens and preserve enough OC to survive his attacks.','His turn end: he can reclaim a central objective during movement or combat.'],
 ['2VP for destroying a unit that started his turn in terrain','Avoid unsupported, easily killed units in terrain unless they buy points or a useful screen. Keep valuable units genuinely hidden. Do not abandon protective terrain just to deny 2VP.','Check where your unit was at the start of his turn. The award is once per turn, not per casualty or unit.'],
 ['5VP if his territory contains no enemy units wholly within it at game end','Preserve a mobile or reserve unit for a protected late entry wholly into his half. A survivor doing your Vanguard Operation may also deny these points.','End of battle. If he has the final turn, it must survive that turn; entering his half earlier is not sufficient.'],
 ]}/><p><strong>Practical priority:</strong> deny an affordable 4VP objective before chasing a boat that does not affect scoring. Use Rubrics or supporting fire to remove exposed Kabalites, Wyches or Reavers, then ensure your own OC actually takes control. Clear his last central holder when feasible to deny the separate 3VP; do not sacrifice Magnus just to force that denial.</p><p><strong>Your missions can reinforce each other:</strong> a cheap survivor in an enemy-half terrain area can perform your 4VP action and, if it remains wholly in that half until game end, deny his 5VP. Keep the two timing checks separate. His home objective is worth a possible 10VP to you at game end, but does not contribute to his 4VP-per-non-home scoring.</p><p><a href={`${base}/reference/11th-edition/cards/reconnaissance/search-and-scour.png`}>Search and Scour scoring card</a> · <a href={`${waha}Kabalite-Warriors`}>Kabalite sticky-control rule</a></p></section>
<LayoutA/><ThreatMap/><ShootingTable/><section><h2>PA vs Recon map reference</h2><p>Your agreed map is layout A, page 48. Layouts B/C remain below for reference; the deployment plan above uses A only. The PA-vs-Purge and PA-vs-Take-and-Hold examples on other pages are different terrain.</p><div className="drukhari-maps">{[48,49,50].map((page,i)=><figure key={page}><a href={`${base}/reference/11th-edition/maps/layout-${page}.jpg`}><img src={`${base}/reference/11th-edition/maps/layout-${page}.jpg`} alt={`Reconnaissance vs Priority Assets terrain layout ${'ABC'[i]}, page ${page}`} loading="lazy"/></a><figcaption>Layout {'ABC'[i]} · page {page}<br/><Link href={`/planner/?layout=reconnaissance-vs-priority-assets-${'abc'[i]}`}>Open in deployment planner →</Link></figcaption></figure>)}</div></section>
<section id="plan"><h2>How your Thousand Sons should approach it</h2><p><strong>Break the delivery system, then remove the exposed passengers.</strong> This army combines fragile scoring units with multiple protected melee packages and mobile lance shooting. A boat kill matters most when you also have the next activation ready to shoot its passengers. Allocate separate shooting units: do not assume the unit destroying a transport can redirect already-declared attacks into the survivors.</p><Table headers={['Your pieces','Deployment / task','Main danger']} rows={[
 ['Magnus','Behind a real obscuring ruin with two exits; support one near-central fight. Delay exposure until you can remove a boat or lance unit decisively.','Ten listed dark lances and six heat lances across the army; do not give several units simultaneous firing angles.'],
 ['Scarabs + Terminator Sorcerer','Prefer starting behind an adjacent ruin for a reliable counterattack. Keep Crystal as a repositioning option, including later mission access.','Incubi’s anti-Infantry devastating wounds, Shrine tokens, and Drazhar’s 6″ combat movement.'],
 ['Two Rubric/Sorcerer units','Cover the two approaches to your chosen objective. Use shooting to clear exposed Wyches, Incubi and scoring bodies.','Two distinct anti-Overwatch protections mean flamers are not a universal charge deterrent.'],
 ['Standalone Disc Sorcerer','Hide behind the main force; preserve ritual support and Incandaeum for a decisive damage turn.','Fast Precision characters; do not put him in a screening line.'],
 ['Tzaangors and Spawn','Screen one approach at a time. Spawn can threaten scoring; keep a second cheap piece ready to replace the first.','Flying boats can bypass an open screen end; Drazhar may reach valuable pieces after the first screen dies.'],
 ['Spear/bow Enlightened','Stage towards an enemy-half terrain action route and cover landing gaps. Commit when they can actually complete the action.','Do not advance and assume the action remains available; avoid gifting an easy Search and Scour kill.'],
 ['Sekhetar Robots','Hold rear space and support short-range attacks on exposed vehicles when safe.','Do not send them unsupported into a lane covered by several lances.'],
 ['Winged Prince','Reserve if there is a safe Rapid Ingress pocket; otherwise stage hidden to counterattack.','Ingress is exposure to the rest of Seb’s turn. Flying transport repositioning and fast bikes can close a pocket.'],
 ]}/><ol><li><strong>Before deployment:</strong> record passengers, Venom splits, special weapons and Malys’s redeploys. Mark the action terrain and the lane you can contest repeatedly.</li><li><strong>Opening:</strong> keep Magnus and Scarabs mutually supporting. Contest Seb’s objective income without exposing both damage pieces. Observe Raider modes and available CP/Pain tokens before measuring threats.</li><li><strong>First exchange:</strong> remove the nearest delivery boat only if its payload can be managed. Otherwise remove a scoring unit or a lance angle. A 4++ Night Shield can change the boat-kill calculation.</li><li><strong>After disembarkation:</strong> shoot the vulnerable bodies; avoid charging Lelith’s Fights First unit with valuable Infantry. Prevent an empty Venom from picking survivors up if you can do so without overextending.</li><li><strong>Later turns:</strong> repeatedly complete Vanguard Operation where feasible and retain a non-home objective. Preserve a late unit wholly in his territory to deny his endgame 5VP; test the enemy home objective for your potential 10VP.</li></ol><p>The anti-Infantry rules are reasons to treat Scarabs carefully, not reasons to deploy Magnus in the open. Conversely, Incubi’s Infantry-only devastating-wound ability and Reaver fly-by do not apply to Magnus. Wych Cult’s baseline Lethal Hits also excludes Monsters, but Planned Strikes can remove that exclusion for a unit.</p><p><Link href="/tactics/screening/">Screening diagrams</Link> · <Link href="/threat-ranges/">Threat calculator</Link> · <a href="https://github.com/kaashif/40k-planner/blob/main/armies/thousand-sons-2000.json">Your supplied Thousand Sons roster</a></p></section>
<section id="meta"><h2>Seb’s list versus actual successful Listhammer rosters</h2><p><strong>Yes: a recognisable competitive variant of this archetype.</strong> Actual roster exports checked on 26 September 2026, not just detachment labels. All three comparisons use Exhibition of Slaughter + Skysplinter Assault and Reconnaissance, in 11th edition. All share Malys, Lelith, a Periapt Succubus, Incubi, Wyches, Mandrakes, Reavers and two heavy-weapon Scourge units.</p><Table headers={['Roster / result','Melee bodies','Transports','Important differences from Seb']} rows={[
 ['Seb · supplied LGT export, 16 Sep','15 Incubi (10 + 5); 20 Wyches','2 Raiders + 3 Venoms','Malys + 10 Incubi; Drazhar + 5; Shroud Archon + Kabalites. One Ravager, one Cronos, two Reaver units. Scourges: four dark lances + four heat lances.'],
 ['Xabier Eceiza · Leithal Hits, 19 Sep · 4–1','15 Incubi (10 + 5); 30 Wyches','1 Raider + 5 Venoms','Shroud Archon leads 10 Incubi; Malys leads 5. No Drazhar. Hand of the Archon, three Cronos models in two units, one Reaver unit; eight dark-lance Scourges. No Ravager/Kabalites.'],
 ['Neil Goldsmith · Port City, 12 Sep · 5–0','10 Incubi (5 + 5); 50 Wyches','1 Raider + 3 Venoms','Malys and Drazhar lead five each; no Archon. Two Hellion units, Kharseth, two Reaver units; eight dark-lance Scourges. No Ravager, Cronos or Kabalites.'],
 ['Zack Dragas · North Coast, 12 Sep · 4–1','20 Incubi (10 + 5 + 5); 40 Wyches','2 Raiders + 4 Venoms','Same five character choices as Seb, but Shroud Archon leads 10 Incubi; Malys and Drazhar five each. One Reaver unit; eight dark-lance Scourges. No Ravager, Cronos or Kabalites.'],
 ]}/><p>Source rosters and results: <a href="https://listhammer.info/players/c768002b5909b9d984">Xabier Eceiza</a> · <a href="https://listhammer.info/players/f6de4fc416808ac5a1">Neil Goldsmith</a> · <a href="https://listhammer.info/players/df2d4df588828965eb">Zack Dragas</a> · <a href="https://listhammer.info/?faction=Drukhari">Drukhari results and roster feed</a>. Neil’s comparison is specifically September’s Port City roster, not his older RocHard result. Counts preserve the submitted exports; occasional differing printed costs are not silently normalised.</p><p><strong>What changes for your game:</strong> Seb has fewer Wych bodies to trade and score with, but a broader shooting package: ten dark lances and six heat lances across the army. Every comparison uses two dark-lance Scourge units; Seb swaps one to heat lances and adds the Ravager. Zack is closest in character selection and transport structure; none is an exact copy. Seb’s Shroud protects his attached Kabalites after disembarking, not Malys’s large Incubi unit. His Succubus-led Wyches still have their own snap-shooting protection, so Rubric Overwatch is not a universal answer.</p><p><strong>Verdict:</strong> prepare for a proven mobile melee-and-scoring archetype with more varied shooting, rather than dismissing it as an off-meta character collection. These three successful rosters demonstrate competitive precedent; the feed selects undefeated/X–1 finishes at qualifying events and cannot establish faction win rate, archetype popularity or Seb’s own performance.</p></section>
<section id="rules"><h2>Power from Pain and the two detachments</h2><p><strong>Power from Pain:</strong> Seb gains a token at the start of his Command phase, when an enemy unit dies, and when an enemy fails Battle-shock. Spend at the timing printed on a unit’s Pain ability; empowerment lasts that phase. One attached-unit empowerment activates both leader and bodyguard Pain abilities. It is not a universal army-wide reroll. <a href={`${waha}#Power-from-Pain`}>Army rule</a></p><p><strong>Skysplinter Assault, 2DP — Rain of Cruelty:</strong> disembarking Drukhari gain Ignores Cover for ranged weapons and Lance for melee through that turn. This rewards shooting and charging after delivery. <a href={`${waha}#Skysplinter-Assault`}>Skysplinter rules</a></p><p><strong>Exhibition of Slaughter, 1DP — Exacting Cruelty:</strong> Wych Cult melee gains Lethal Hits against targets other than Monsters/Vehicles. It covers Wyches, their Wych Cult characters and Reavers; not every Drukhari unit. This is the Wych Cult-tagged detachment in the pairing. <a href={`${pack}#page=2`}>Official detachment</a> · <a href={`${waha}#Exhibition-of-Slaughter`}>Wahapedia</a></p><h3>The two purchased enhancements</h3><p><strong>Nightmare Shroud, 20pts, Archon:</strong> his unit cannot be attacked using Fire Overwatch during a turn in which it disembarked. It does not protect Malys or Drazhar elsewhere. <a href={`${waha}#Skysplinter-Assault`}>Enhancement</a></p><p><strong>Periapt of Torments, 20pts, Succubus:</strong> snap-shooting immunity for her unit. Short verbatim excerpt: <q>Enemy units cannot target this unit with snap shooting attacks.</q> This blocks that attack type, including Overwatch, without the Shroud’s disembark trigger. <a href={`${pack}#page=2`}>Official wording</a></p><h3>All nine detachment stratagems — each costs 1CP before modifiers</h3><div className="reserve-table-wrap"><table><thead><tr><th>Stratagem</th><th>Timing / target</th><th>Effect and implication</th></tr></thead><tbody>{strata.map(([name,det,timing,effect])=><tr key={name}><th><a href={`${waha}#${det==='Exhibition'?'Exhibition-of-Slaughter':name.toUpperCase().replaceAll(' ','-')}`}>{name}</a><small>{det}</small></th><td>{timing}</td><td>{effect}</td></tr>)}</tbody></table></div><p>Archon’s discount and Malys’s nearby CP tax make CP tracking important. A cheaper stratagem is not permission to repeat it beyond the core usage limits. None of these rules gives automatic army-wide Scout moves or charge rerolls.</p></section>
<section id="threats"><h2>Threat distances and what actually enables them</h2><p>These are open-ground, straight-line planning limits, measured from the starting nearest model edge (hull for FRAME vehicles) to the target’s nearest edge. Terrain, pivots, wholly-within disembark placement and coherency can reduce reach. The 80% column gives a distance reached with at least that probability; 50% uses the planner’s median convention. Rerolls only apply in the row that names them.</p><Table headers={['Package','Segments','80% reach','50% reach','Maximum','Required rule']} rows={threatRows}/><p><strong>Venom warning:</strong> the current Rapid Deployment wording instructs a <em>shock disembark</em> after its advance. Core §18.07 does not add the normal rapid-disembark charge ban; the passenger itself did not advance. On that combined wording, passengers can charge if otherwise eligible. This is a rules interaction inferred from the linked texts, not a generic permission for every transport’s passengers. Do not apply the old assumption that advancing the boat always prevents a passenger charge. <a href={`${waha}Venom`}>Venom</a> · <a href={`${core}#Transports`}>Core §§18.04–18.07</a></p><p><strong>No double-counted passenger movement:</strong> the moved-transport rows include its move, passenger placement, then charge. They do not add a further 7″/8″ Infantry move. A tactical disembark before the boat moves is a different sequence. Raider’s 6″ Wych mode must be selected in Command; it is not simultaneously the boat’s advance/charge-reroll mode.</p><p><strong>Charge tokens:</strong> for advancing Succubus-led Wyches, empower via Wyches at the <em>start</em> of the Charge phase: that permits the charge and activates the Succubus’s charge reroll. A Movement-phase token for the advance reroll does not persist into Charge. Short Wyches excerpt: <q>eligible to declare a charge in a turn in which it Advanced or Fell Back.</q> <a href={`${waha}Wyches`}>Wyches</a> · <a href={`${waha}Succubus`}>Succubus</a></p><p><strong>Shooting reach:</strong> Ravager/Raider dark lances reach 50″ after a 14″ normal move; Scourge dark lances also reach 50″, then the unit can withdraw 6″. Heat-lance Scourges reach 32″ after normal movement, or up to 38″ advancing with Assault; Melta 3 applies only within 9″. Empowered Reavers advance a fixed 24″ and can fire their Assault heat lance to 42″, with the melta band reaching 33″. These are range envelopes, not guarantees of visibility.</p><h3>Transport assignments: one possible manifest, not confirmed</h3><Table headers={['Transport','Example passengers','Capacity']} rows={[
 ['Raider 1','Malys + 10 Incubi','11/11'],['Raider 2','Lelith + 10 Wyches','11/11'],['Venom 1','Drazhar + 5 Incubi','6/6'],['Venom 2','Archon + 5 split Kabalites','6/6'],['Venom 3','Other 5 split Kabalites','5/6'],['On foot / reserves','Succubus + 10 Wyches; other units as declared','Not assigned a transport in this example'],
 ]}/><p>He can choose different legal splits and passengers. A full Wych squad plus leader cannot fit into a Venom. Each Venom permits a qualifying squad split before attachments; identify the exact models in each half. Boat rules and enhancement protection depend on the actual manifest.</p><h3>Deep Strike and screening</h3><p>Both Raiders, all three Venoms, the Ravager, Mandrakes and both Scourge units have native Deep Strike. Embarked passengers can arrive with their transport; arrival and disembark restrictions still apply. Malys can redeploy three units, including into Strategic Reserves. Mandrakes can also leave the table through their Pain ability. No general 6″ Deep Strike permission was established for this list: use the planner’s 8″ zone for standard arrivals, then account for any explicitly declared exception. <a href={`${core}#Strategic-Reserves`}>Reserves rules</a></p></section>
<section id="glossary"><h2>Reading the profiles</h2><p><strong>M</strong> is movement in inches; <strong>T</strong> is Toughness; <strong>Sv</strong> is armour save; <strong>W</strong> is wounds per model; <strong>Ld</strong> is the Leadership test threshold; <strong>OC</strong> is objective-control contribution; <strong>Inv</strong> is the invulnerable save. Weapon <strong>A</strong> means attacks per weapon, <strong>BS/WS</strong> the shooting/melee hit threshold, <strong>S</strong> Strength, <strong>AP</strong> armour penetration, and <strong>D</strong> damage per unsaved attack. D3/D6 are dice, not fixed damage.</p><p><strong>Lance:</strong> +1 to wound after charging. <strong>Lethal Hits:</strong> critical hits can automatically wound; those auto-wounds do not themselves become critical wounds. <strong>Sustained Hits X:</strong> extra hits on critical hits. <strong>Devastating Wounds:</strong> critical wounds bypass saves as mortal damage, with its per-attack spill restriction. <strong>Anti-X:</strong> its listed wound-roll threshold critically wounds that target type. <strong>Precision:</strong> can allocate a successful wound to a visible attached Character. <strong>Twin-linked:</strong> wound rerolls. <strong>Extra Attacks:</strong> attack with that melee weapon in addition.</p><p><strong>Assault:</strong> permits those weapons to shoot after advancing; does not permit a charge. <strong>Heavy:</strong> +1 to hit when stationary. <strong>Torrent:</strong> automatic hits. <strong>Melta X:</strong> extra damage within half range. <strong>Stealth:</strong> −1 to incoming ranged hit rolls. <strong>Feel No Pain:</strong> separate wound-loss prevention. <strong>Hazardous:</strong> a post-attack risk to the firing/fighting unit. <strong>Firing Deck:</strong> the transport uses selected embarked models’ weapons; it does not automatically inherit all passenger abilities. <strong>Fights First:</strong> changes fight priority; check the core sequencing before charging Lelith. <a href={`${core}#Abilities`}>Core abilities and definitions</a></p></section>
<section id="units"><h2>Every listed unit: profiles, weapons and abilities</h2><p>Profiles below describe the supplied equipment. Counts are in each unit’s introduction; weapon attacks are per equipped model/weapon, not automatically the whole unit. Unit-wide buffs are explained separately so base profiles do not silently include every possible bonus.</p>{units.map(u=><article className="vod-game drukhari-unit" id={u.slug} key={u.slug}><h3><a href={`${waha}${u.slug}`}>{u.name} ↗</a></h3><p>{u.loadout}</p><Table headers={['M (inches)','T','Sv','W/model','Ld','OC/model','Inv']} rows={[u.stats.split('|')]}/><Table headers={['Equipped weapon','Range','A','BS/WS','S','AP','D','Traits']} rows={u.weapons}/><ul>{u.abilities.map(a=><li key={a}>{a}</li>)}</ul><p><strong>Against your Thousand Sons:</strong> {u.impact}</p><p><a href={`${waha}${u.slug}`}>Complete datasheet, exact wording and applicable stratagems →</a></p></article>)}</section>
<section><h2>Sources and scope</h2><p>The list and its event/upload details come from your pasted BCP export; no BCP roster permalink was supplied. The rules are checked against the linked 11th-edition Wahapedia pages and official faction amendments, rather than assuming the September 16 export establishes today’s wording. Short quotations are marked; all other ability explanations are paraphrases.</p><p><a href={waha}>Drukhari army and detachments</a> · <a href={pack}>Official Drukhari faction pack v1.2</a> · <a href={core}>Core rules</a> · <a href={`${base}/reference/11th-edition/data/event-layouts.json`}>Mission-pairing data</a> · <a href={`${base}/matchups/drukhari/seb-units.json`}>Saved unit reference</a></p></section>
</main>}
