'use client';
import { useState } from 'react';
import Link from 'next/link';
import layouts from '../../../public/matchups/world-eaters-deployments.json';
const base=process.env.NEXT_PUBLIC_BASE_PATH??'';
function odds(required:number,reroll:boolean){const p=Array.from({length:36},(_,i)=>Math.floor(i/6)+i%6+2).filter(v=>v>=required).length/36;return 100*(reroll?1-(1-p)**2:p);}
export default function Examples(){
 const [enemy,setEnemy]=useState<'angron'|'eightbound'>('angron');
 const [gap,setGap]=useState(24);const [bonus,setBonus]=useState(true);const [reroll,setReroll]=useState(false);
 const move=enemy==='angron'?14:16;const remaining=gap-move;const eligible=remaining<=12;const required=Math.max(2,Math.max(3,Math.ceil(remaining))-(bonus?1:0));const chance=eligible?odds(required,reroll):0;
 return <><section className="vod-focus"><h2>Open-ground charge examples</h2><p>One selected threat from its initial deployment position. Eightbound assumes an unobstructed full Scout move. No extra moves, surge triggers, casualties, terrain costs or intervening units. Charge-roll re-roll only; blessing already active when checked.</p><label>Threat <select value={enemy} onChange={e=>setEnemy(e.target.value as typeof enemy)}><option value="angron">Angron · 14″ move</option><option value="eightbound">Regular Eightbound · 6″ Scout + 10″ move</option></select></label><p><label>Initial base-to-base gap: <strong>{gap}″</strong> <input aria-label="Initial base-to-base gap" type="range" min="18" max="34" step="1" value={gap} onChange={e=>setGap(Number(e.target.value))}/></label></p><p><label><input type="checkbox" checked={bonus} onChange={e=>setBonus(e.target.checked)}/> +1 charge blessing active</label> · <label><input type="checkbox" checked={reroll} onChange={e=>setReroll(e.target.checked)}/> Re-roll a failed charge roll</label></p><p role="status">{eligible?`After up to ${move}″ of movement: ${remaining<=2?"just over 2":remaining}″ gap. Needs ${required}+ on 2D6${bonus?' with +1 charge':''}. Success: ${chance.toFixed(1)}%.`:`After ${move}″ of movement: ${remaining}″ gap. This target is beyond 12″: no direct charge, even with +1 and a re-roll.`}</p><p>These percentages are dice calculations, not predictions of success through terrain. The diagrams below keep their example placements fixed when you move the calculator slider.</p></section>
 <p>Choose either colour side by agreement in your game; these examples assign WE to red and TS to teal. Maps use the planner’s landscape orientation, rotated relative to the linked portrait artwork. Positions are practice suggestions, not VOD observations or a validated complete deployment.</p>
 {layouts.map(l=>{const origin=l[enemy];const radius=enemy==='angron'?100/25.4/2:40/25.4/2;const reach=enemy==='angron'?26:28;const magnus=l.units.find(u=>u[0]==='Magnus')!;const distance=Math.hypot(Number(magnus[1])-origin[0],Number(magnus[2])-origin[1])-radius-Number(magnus[3]);return <section className="vod-game" id={`layout-${l.variant.toLowerCase()}`} key={l.variant}><h2>Layout {l.variant}</h2><p>{l.note}</p><p><Link href={`/planner/?layout=${l.plannerId}`}>Open editable planner</Link> · <a href={`${base}/reference/11th-edition/layouts/layout-${32+'ABC'.indexOf(l.variant)+1}.jpg`}>Full terrain artwork</a></p><svg viewBox="-1 -2 62 48" role="img" aria-label={`Layout ${l.variant}: suggested Thousand Sons positions and ${enemy} maximum reach`} style={{width:'100%',maxWidth:1050,display:'block',margin:'20px 0',background:'#111e24'}}>
 <defs><clipPath id={`clip-${l.variant}`}><rect width="60" height="44"/></clipPath></defs><g clipPath={`url(#clip-${l.variant})`}><rect width="60" height="44" fill="#101a20"/>{l.zones.map(z=><polygon key={z.id} points={z.points.map(p=>`${p.x},${p.y}`).join(' ')} fill={z.type==='player'?'#16413d':'#4c2533'} stroke={z.type==='player'?'#78e3d0':'#f8a5c5'} strokeWidth=".12"/>)}
 {l.terrain.map((t,i)=><polygon key={i} points={t.points.map(p=>`${p.x},${p.y}`).join(' ')} fill={t.base?'#34434b':t.category==='DENSE'?'#688970':'#b79c6e'} stroke="#91a0a6" strokeWidth=".06" opacity=".85"/>)}
 <circle cx={origin[0]} cy={origin[1]} r={reach+radius} fill="#f18b7a" fillOpacity=".05" stroke="#ffb69f" strokeWidth=".25" strokeDasharray=".5 .4"/><circle cx={origin[0]} cy={origin[1]} r={radius} fill="#bb4763" stroke="#ffd1db" strokeWidth=".12"/>
 <text x={origin[0]} y={origin[1]-radius-.6} textAnchor="middle" fill="#fff" fontSize="1">{enemy==='angron'?'Angron':'Eightbound'} start</text>
 {l.units.map(u=>{const x=Number(u[1]),y=Number(u[2]),r=Number(u[3]);return <g key={String(u[0])}><circle cx={x} cy={y} r={r||.5} fill="#2f8d83" stroke="#b4fff0" strokeWidth=".12"/><text x={x} y={y-(r||.5)-.35} textAnchor="middle" fill="#e1fff8" fontSize=".8" paintOrder="stroke" stroke="#102128" strokeWidth=".2">{String(u[0])}</text></g>})}</g><rect width="60" height="44" fill="none" stroke="#afbdc5" strokeWidth=".15"/><text x="1" y="45.4" fill="#c7d4db" fontSize=".9">60″ × 44″ · dashed line = maximum reach to target’s nearest base edge</text></svg>
 <p><strong>Example {enemy==='angron'?'Angron':'Eightbound'} → Magnus gap: {distance.toFixed(1)}″.</strong> {distance>reach?'Outside this selected unit’s direct first-turn reach.':'Inside the maximum envelope: this is not a safe distance against this selected threat.'} A different enemy starting position changes this measurement.</p><p>Magnus uses a 100mm base circle. All other markers are unit-group anchors, not base footprints: place every model legally inside your zone, check coherency and wall/base clearance, and measure to the nearest actual model. A group anchor outside a threat envelope does not prove its whole unit is outside. Winged Prince starts in reserve; both bow units from the supplied export are shown.</p><p>The shaded threat envelope ignores walls and legal landing space; it is an upper bound, not a legal route. Blocking line of sight alone does not stop a charge. These positions do not certify protection from the Forgefiends. Adjust after seeing their lanes and the actual terrain heights.</p></section>})}
 <p className="vod-small">Terrain geometry: <a href="https://rapidingress.com/layout-updates">Rapid Ingress / GDM, 26 August revision</a>, already synchronized in the planner. <a href="https://github.com/kaashif/40k-planner/blob/main/docs/world-eaters-threat-ranges.md">Rules, distance tables and worked examples</a>.</p></>;
}
